### ISSUE TITLE
Neutral Density Product of WFS

### ISSUE THREAD

**Issue by ZhuxiaoLi66** [NOAA-SWPC/GSMWAM-IPE#62]
Total Neutral Density products are based on operational WAM-IPE (WFS) output, with calculated Helium on the higher levels based on MSIS2.0.  The products are at fixed-hights from 100km to 1000km with 10km intervals.

**Comment by ZhuxiaoLi66** [comment]
The new products of Neutral Density during the period of 2021100121-2021101821 have been produced and validated.
The following plots are part of the validation. 
![DEN_prod_400km_Oct2_2021](https://user-images.githubusercontent.com/22546571/144905652-3ffe9d6a-1a1e-4c86-b5c2-567fda7e4655.png)
![DEN_prod_400km_Oct6_2021](https://user-images.githubusercontent.com/22546571/144905746-48f82f83-3ce7-4b0b-a7d3-aa923400cdf0.png)
![DEN_prod_800km_Oct10_2021](https://user-images.githubusercontent.com/22546571/144905774-9207f729-3c49-41f2-88cc-d350647599f2.png)

**Comment by twfang** [comment]
@ZhuxiaoLi66 I think it will be good to divide the product based on days and each file should start from 0UT. Otherwise, the file size becomes too large to transfer and no timestamps are provided in the file. I have been using WAM_den_yyyymmdd.nc as a default file name. Please let me know if you have any questions. Thanks!
